"""add_api_layer_tables

Adds the HTTP API persistence layer: ``api_users`` (auth) and
``api_jobs`` (sync invocation log with ``needs_verification`` state
machine + the ``api_job_status_enum`` Postgres enum).

Revision ID: ef2c7288bbb0
Revises: b4117e0c3dd4
Create Date: 2026-05-12 16:56:07.515686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef2c7288bbb0"
down_revision: Union[str, None] = "b4117e0c3dd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_jobs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("trigger_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "needs_verification",
                "verified",
                "failed",
                name="api_job_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "result", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("verified_by", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "finished_at IS NULL OR status <> 'running'",
            name=op.f("ck_api_jobs_finished_at_only_when_not_running"),
        ),
        sa.CheckConstraint(
            "verified_at IS NULL OR status = 'verified'",
            name=op.f("ck_api_jobs_verified_at_only_when_verified"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_jobs")),
    )
    op.create_index(
        op.f("ix_api_jobs_started_at"),
        "api_jobs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_jobs_status"), "api_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_api_jobs_trigger_name"),
        "api_jobs",
        ["trigger_name"],
        unique=False,
    )
    op.create_table(
        "api_users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("worker_key", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_users")),
        sa.UniqueConstraint("username", name=op.f("uq_api_users_username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_users")
    op.drop_index(op.f("ix_api_jobs_trigger_name"), table_name="api_jobs")
    op.drop_index(op.f("ix_api_jobs_status"), table_name="api_jobs")
    op.drop_index(op.f("ix_api_jobs_started_at"), table_name="api_jobs")
    op.drop_table("api_jobs")
    # ### end Alembic commands ###
