"""add_email_to_api_users

Revision ID: c03728fbb1cf
Revises: ef2c7288bbb0
Create Date: 2026-06-13 01:20:42.537575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c03728fbb1cf"
down_revision: Union[str, None] = "ef2c7288bbb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_users", sa.Column("email", sa.String(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_api_users_email"), "api_users", ["email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_api_users_email"), "api_users", type_="unique")
    op.drop_column("api_users", "email")
    # ### end Alembic commands ###
