"""add_sync_prefs_to_api_users

Revision ID: 69dde0d17ff2
Revises: 10b7dc50b00f
Create Date: 2026-06-24 19:06:06.830172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69dde0d17ff2"
down_revision: Union[str, None] = "10b7dc50b00f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_users",
        sa.Column(
            "sync_prefs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_users", "sync_prefs")
    # ### end Alembic commands ###
